### ISSUE TITLE
Can't install nor find molenc_ph4.py [question]

### ISSUE THREAD

**Issue by SusannaDiV** [UnixJunkie/ACP4#11]
Hi!

I can't seem to run the makefile locally, would it be possible to get a small instruction as to the required packages (eg. ocaml switch version)? Also, molenc_ph4.py cited the README has been renamed to acp4_ph4.py, right?

Thank you in advance!

**Comment by UnixJunkie** [comment]
Yes, apparently acp4_ph4.py is the current script name.

**Comment by UnixJunkie** [comment]
Try to install using the packaged version in opam: acp4 v1.0.1.
If you have opam installed and configured:
```bash
opam install acp4
```
should be all you need to do.
Talk to a unix sysadmin if you have problems installing the software.

**Comment by UnixJunkie** [comment]
ACP4 is supposed to work well w/ OCaml >= 4.08.
I am using OCaml-5.1.1 these days.

Please reopen if you have other questions.
